---
- name: Let's copy our executable script to remote location, execute script and get result back.
  remote_user: root
  hosts: all
  tasks:
     - name: Transfer executable script script
       copy: src=/home/ec2-user/hello.sh dest=/home/ec2-user mode=0777
     - name: running the script file
       command: sh /home/ec2-user/hello.sh
...

