---
- name: Let's copy our executable script to remote location, execute script and get result back.
  remote_user: root
  hosts: 54.89.12.167
  tasks:
     - name: Transfer executable script script
       copy: src=/var/lib/jenkins/workspace/Pipeline/script.sh dest=/var/lib/jenkins/workspace/Pipeline mode=0777
     - name: running the sript file
       command: sh /var/lib/jenkins/workspace/Pipeline/script.sh
...

